### ISSUE TITLE
rdf 1.1

### ISSUE THREAD

**Issue by PaulZH** [dice-group/LIMES#112]
I get following error:
org.apache.jena.sparql.resultset.ResultSetException: Both language and datatype defined: { 
  "xml:lang" : "nl" ,
  "datatype" : "http://www.w3.org/1999/02/22-rdf-syntax-ns#langString" ,
  "type" : "literal" ,
  "value" : "Rue du Château"
}
	at org.apache.jena.sparql.resultset.JSONInput.parseOneTerm(JSONInput.java:214)
	at org.apache.jena.sparql.resultset.JSONInput.parse(JSONInput.java:172)
	at org.apache.jena.sparql.resultset.JSONInput.process(JSONInput.java:100)
	at org.apache.jena.sparql.resultset.JSONInput.fromJSON(JSONInput.java:63)
	at org.apache.jena.query.ResultSetFactory.fromJSON(ResultSetFactory.java:331)
	at org.apache.jena.sparql.engine.http.QueryEngineHTTP.execResultSetInner(QueryEngineHTTP.java:385)
	at org.apache.jena.sparql.engine.http.QueryEngineHTTP.execSelect(QueryEngineHTTP.java:351)
	at org.aksw.limes.core.io.query.SparqlQueryModule.fillCache(SparqlQueryModule.java:90)
	at org.aksw.limes.core.io.query.SparqlQueryModule.fillCache(SparqlQueryModule.java:40)
	at org.aksw.limes.core.io.cache.HybridCache.getData(HybridCache.java:129)
	at org.aksw.limes.core.io.cache.HybridCache.getData(HybridCache.java:93)
	at org.aksw.limes.core.gui.model.Endpoint.getCache(Endpoint.java:88)
	at org.aksw.limes.core.gui.model.Config$1.call(Config.java:349)
	at org.aksw.limes.core.gui.model.Config$1.call(Config.java:346)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

In the spec I read:
A literal in an RDF graph consists of two or three elements:
    a lexical form, being a Unicode [UNICODE] string, which SHOULD be in Normal Form C [NFC],
    a datatype IRI, being an IRI identifying a datatype that determines how the lexical form maps to a literal value, and
    if and only if the datatype IRI is http://www.w3.org/1999/02/22-rdf-syntax-ns#langString, a non-empty language tag as defined by [BCP47].

Paul

**Comment by Kleanthi** [comment]
Dear Paul,

this seems to be an error of Jena. Are you sure that the lexical form is in fact a UNICODE string?

**Comment by PaulZH** [comment]
will check and come back.

**Comment by PaulZH** [comment]
Is utf-8

**Comment by Kleanthi** [comment]
The error received wasn't able to be reproduced locally. It seems to be an error of encoding of the data and Jena's/
