### ISSUE TITLE
HTTP 502 error

### ISSUE THREAD

**Issue by akirsche** [dice-group/LIMES#137]
Hello LIMES team,

Recently, I constantly receive the error below from LIMES-core, when attempting to access linkedgeodata endpoint with the following configuration:

```
@prefix geo:   <http://www.w3.org/2003/01/geo/wgs84_pos#> .
@prefix dbo:   <http://dbpedia.org/ontology/> .
@prefix lgdo:  <http://linkedgeodata.org/ontology/> .
@prefix owl:   <http://www.w3.org/2002/07/owl#> .
@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .
@prefix limes: <http://limes.sf.net/ontology/> .

limes:1509372119553_source
        a                  limes:SourceDataset ;
        rdfs:label         "dbpedia" ;
        limes:endPoint     <http://dbpedia.org/sparql> ;
        limes:pageSize     "-1" ;
        limes:property     "rdfs:label" , "geo:lat" , "geo:long" ;
        limes:restriction  "?x a dbo:Airport" ;
        limes:type         "sparql" ;
        limes:variable     "?x" .

limes:1509372119553_acceptance
        a                limes:Acceptance ;
        limes:file       "dbp-lgd-aiport-accept.nt"  ;
        limes:relation   owl:sameAs ;
        limes:threshold  "0.9" .

limes:1509372119553_metric
        a                 limes:Metric ;
        limes:expression  "and(euclidean(x.geo:long,y.geo:long)|0.99,euclidean(y.geo:lat,x.geo:lat)|0.99)" .

limes:1509372119553_review
        a                limes:Review ;
        limes:file       []  ;
        limes:relation   owl:sameAs ;
        limes:threshold  "0.7" .

limes:1509372119553  a           limes:LimesSpecs ;
        limes:executionEngine    "default" ;
        limes:executionPlanner   "default" ;
        limes:executionRewriter  "default" ;
        limes:granularity        "2" ;
        limes:hasAcceptance      limes:1509372119553_acceptance ;
        limes:hasMetric          limes:1509372119553_metric ;
        limes:hasReview          limes:1509372119553_review ;
        limes:hasSource          limes:1509372119553_source ;
        limes:hasTarget          limes:1509372119553_target ;
	limes:outputFormat "NT" .

limes:1509372119553_target
        a                  limes:TargetDataset ;
        rdfs:label         "linkedgeodata" ;
        limes:endPoint     <http://linkedgeodata.org/sparql> ;
        limes:pageSize     "-1" ;
        limes:property     "geo:long" , "geo:lat" , "rdfs:label" ;
        limes:restriction  "?y a lgdo:Airport" ;
        limes:type         "sparql" ;
limes:variable "?y" .
```

```
 org.apache.jena.sparql.engine.http.QueryExceptionHTTP: HTTP 502 error making the query: Proxy Error
        at org.apache.jena.sparql.engine.http.HttpQuery.rewrap(HttpQuery.java:411)
        at org.apache.jena.sparql.engine.http.HttpQuery.execGet(HttpQuery.java:355)
        at org.apache.jena.sparql.engine.http.HttpQuery.exec(HttpQuery.java:292)
        at org.apache.jena.sparql.engine.http.QueryEngineHTTP.execResultSetInner(QueryEngineHTTP.java:359)
        at org.apache.jena.sparql.engine.http.QueryEngineHTTP.execSelect(QueryEngineHTTP.java:351)
        at org.aksw.limes.core.io.query.SparqlQueryModule.fillCache(SparqlQueryModule.java:90)
        at org.aksw.limes.core.io.query.SparqlQueryModule.fillCache(SparqlQueryModule.java:40)
        at org.aksw.limes.core.io.cache.HybridCache.getData(HybridCache.java:129)
        at org.aksw.limes.core.io.cache.HybridCache.getData(HybridCache.java:93)
        at org.aksw.limes.core.controller.Controller.getMapping(Controller.java:144) 
```
The error occurrs both in release 1.2.0 and in release 1.2.1 .

Thanks in advance for your help,
Amit

**Comment by Kleanthi** [comment]
Sorry to get back to you with such delay.
Have you tried to run a query against both endpoints? It might be that at that time they were not reachable cause they were overloaded with requests. Also can you please check your proxy/firewall settings?

**Comment by MSherif** [comment]
@Kleanthi Please try to generate the same exception in your machine. In case it works fine in your machine, please close this issue.

**Comment by Kleanthi** [comment]
As requested: I have executed LIMES using the above configuration file and it worked perfectly fine.
