### ISSUE TITLE
Error parsing metric expression

### ISSUE THREAD

**Issue by alicecaporali** [dice-group/LIMES#207]
I run Limes GUI with this commande line : `java -jar target/jfx/app/limes-gui-1.5.8-SNAPSHOT-jfx.jar`

When I load a file configuration and I run a machine learning solution (active learning or batch learning). I got some results and next I try to "Save Linkspecification", I got this error : 
```
Exception in thread "JavaFX Application Thread" org.aksw.limes.core.gui.model.metric.MetricFormatException: Error parsing metric expression "trigrams(x.person1:soc_sec_id,y.person2:soc_sec_id)".
	at org.aksw.limes.core.gui.model.metric.MetricParser.parse(MetricParser.java:180)
	at org.aksw.limes.core.gui.model.Config.setMetricExpression(Config.java:445)
	at org.aksw.limes.core.gui.controller.ResultController.saveLinkSpec(ResultController.java:152)
	at org.aksw.limes.core.gui.view.ResultView.lambda$createWindow$3(ResultView.java:205)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3470)
	at javafx.scene.Scene$ClickGenerator.access$8100(Scene.java:3398)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3766)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:394)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$345(GlassViewEventHandler.java:432)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:431)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$203(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.aksw.limes.core.gui.model.metric.MetricFormatException: There is no node with id "trigrams", creation is not possible.
	at org.aksw.limes.core.gui.model.metric.Node.createNode(Node.java:71)
	at org.aksw.limes.core.gui.model.metric.MetricParser.parsePart(MetricParser.java:145)
	at org.aksw.limes.core.gui.model.metric.MetricParser.parse(MetricParser.java:178)
	... 33 more
```

This is my config file : 
```
[...]
<METRIC>
  trigram(src.foaf:name, target.abes:NOM)
</METRIC>
[...]
```

I try 2 or 3 different config files and I got the same error in recent days. All my config files are generate by the Limes Web UI with the option "Display config". They work on the Limes Web UI without machine learning.

How can I solve this error ?
Tank's

**Comment by kvndrsslr** [comment]
GUI is not supported anymore, closing this
