### ISSUE TITLE
Crossvalidation in Evaluator class is not working

### ISSUE THREAD

**Issue by dobraczka** [dice-group/LIMES#48]
The crossValidate function initializes algorithms without a target cache which leads to errors, since most algorithms rely on having a source AND target cache

**Comment by dobraczka** [comment]
This issue prevents me from pushing since EvaluatorsTest is failing due to a Exception:
java.lang.NullPointerException
	at org.aksw.limes.core.ml.algorithm.euclid.LinearSelfConfigurator.getPropertyStats(LinearSelfConfigurator.java:177)
	at org.aksw.limes.core.ml.algorithm.wombat.AWombat.init(AWombat.java:241)
	at org.aksw.limes.core.ml.algorithm.WombatSimple.init(WombatSimple.java:56)
	at org.aksw.limes.core.ml.algorithm.AMLAlgorithm.init(AMLAlgorithm.java:39)
	at org.aksw.limes.core.evaluation.evaluator.Evaluator.crossValidate(Evaluator.java:200)
	at org.aksw.limes.core.evaluation.EvaluatorsTest.testCrossValidate(EvaluatorsTest.java:76)
	at org.aksw.limes.core.evaluation.EvaluatorsTest.test(EvaluatorsTest.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by kvndrsslr** [comment]
Stale and underspecified, closing this.
