### ISSUE TITLE
EAGLE not working via command line

### ISSUE THREAD

**Issue by mommi84** [dice-group/LIMES#95]
Configuration file **config.xml**:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE LIMES SYSTEM "limes.dtd">
<LIMES>	
	<PREFIX>
		<NAMESPACE>http://www.okkam.org/ontology_restaurant1.owl#</NAMESPACE>
		<LABEL>res</LABEL>
	</PREFIX>
	<PREFIX>
		<NAMESPACE>http://www.w3.org/1999/02/22-rdf-syntax-ns#</NAMESPACE>
		<LABEL>rdf</LABEL>
	</PREFIX>
	<SOURCE>
		<ID>source</ID>
		<ENDPOINT>src/main/resources/datasets/Restaurants/restaurant1.nt</ENDPOINT>
		<VAR>?x</VAR>
		<PAGESIZE>50000</PAGESIZE>
		<RESTRICTION>?x rdf:type res:Restaurant</RESTRICTION>
		<PROPERTY>res:name</PROPERTY>
		<TYPE>NT</TYPE>
	</SOURCE>
	<TARGET>
		<ID>target</ID>
		<ENDPOINT>src/main/resources/datasets/Restaurants/restaurant1.nt</ENDPOINT>
		<VAR>?y</VAR>
		<PAGESIZE>50000</PAGESIZE>		
		<RESTRICTION>?y rdf:type res:Restaurant</RESTRICTION>
		<PROPERTY>res:name</PROPERTY>
		<TYPE>NT</TYPE>
	</TARGET>
	<MLALGORITHM>
        	<NAME>eagle</NAME>
	        <TYPE>supervised batch</TYPE>
	        <TRAINING>src/main/resources/datasets/Restaurants/restaurant1.nt</TRAINING>
	</MLALGORITHM>
	<ACCEPTANCE>
		<THRESHOLD>0.05</THRESHOLD>
		<FILE>predictions.nt</FILE>
		<RELATION>res:sameAs</RELATION>
	</ACCEPTANCE>
	<REVIEW>
		<THRESHOLD>0.01</THRESHOLD>
		<FILE>output_review.nt</FILE>
		<RELATION>res:near</RELATION>
	</REVIEW>
	<EXECUTION>
		<REWRITER>default</REWRITER>
		<PLANNER>default</PLANNER>
		<ENGINE>default</ENGINE>
	</EXECUTION>
	<OUTPUT>TAB</OUTPUT>
</LIMES>
```

Output:
```bash
$ java -Xmx2g -jar target/limes-core-1.1.2-SNAPSHOT.jar config.xml

17:10:04.921 [main] INFO  org.aksw.limes.core.io.cache.HybridCache:111 - Checking for file /Users/tom/PhD/limes/LIMES-dev/limes-core/cache/-960292797.ser
17:10:04.923 [main] INFO  org.aksw.limes.core.io.cache.HybridCache:114 - Found cached data. Loading data from file /Users/tom/PhD/limes/LIMES-dev/limes-core/cache/-960292797.ser
17:10:04.949 [main] INFO  org.aksw.limes.core.io.cache.HybridCache:120 - Cached data loaded successfully from file /Users/tom/PhD/limes/LIMES-dev/limes-core/cache/-960292797.ser
17:10:04.950 [main] INFO  org.aksw.limes.core.io.cache.HybridCache:121 - Size = 113
17:10:04.950 [main] INFO  org.aksw.limes.core.io.cache.HybridCache:111 - Checking for file /Users/tom/PhD/limes/LIMES-dev/limes-core/cache/1365760940.ser
17:10:04.950 [main] INFO  org.aksw.limes.core.io.cache.HybridCache:114 - Found cached data. Loading data from file /Users/tom/PhD/limes/LIMES-dev/limes-core/cache/1365760940.ser
17:10:04.961 [main] INFO  org.aksw.limes.core.io.cache.HybridCache:120 - Cached data loaded successfully from file /Users/tom/PhD/limes/LIMES-dev/limes-core/cache/1365760940.ser
17:10:04.961 [main] INFO  org.aksw.limes.core.io.cache.HybridCache:121 - Size = 113
17:10:05.515 [main] INFO  org.aksw.limes.core.io.config.reader.rdf.RDFConfigurationReader:63 - Opening N-Triples file
17:10:05.641 [main] INFO  org.aksw.limes.core.io.config.reader.rdf.RDFConfigurationReader:72 - Loading src/main/resources/datasets/Restaurants/restaurant1.nt is done in 653ms.
17:10:05.677 [main] INFO  org.aksw.limes.core.ml.algorithm.Eagle:220 - Setting up EAGLE...
17:10:05.693 [main] INFO  org.aksw.limes.core.ml.algorithm.eagle.util.CacheTrimmer:143 - unable to find instance with key http://www.okkam.org/oaie/restaurant1-City48
[...]
17:10:05.809 [main] INFO  org.aksw.limes.core.ml.algorithm.eagle.util.CacheTrimmer:155 - unable to find instance with key oceana
17:10:05.809 [main] INFO  LIMES:266 - Trimming to 113 and 0 caches.
17:10:05.821 [main] INFO  LIMES:71 - Creating basic commands 
17:10:05.895 [main] INFO  org.jgap.gp.impl.GPGenotype:390 - Creating initial population
17:10:05.897 [main] INFO  org.jgap.gp.impl.GPGenotype:391 - Mem free: 123.0 MB
org.jgap.InvalidConfigurationException: java.lang.IllegalStateException: Chromosome (depth 1, index 0) requires a function or terminal of return type class org.aksw.limes.core.datastrutures.PairSimilar (sub return type 1) but there is no such node available
	at org.jgap.gp.impl.GPGenotype.randomInitialGenotype(GPGenotype.java:401)
	at org.jgap.gp.impl.GPGenotype.randomInitialGenotype(GPGenotype.java:315)
	at org.aksw.limes.core.ml.algorithm.eagle.core.ExpressionProblem.create(ExpressionProblem.java:91)
	at org.aksw.limes.core.ml.algorithm.Eagle.setUp(Eagle.java:255)
	at org.aksw.limes.core.ml.algorithm.Eagle.learn(Eagle.java:106)
	at org.aksw.limes.core.ml.algorithm.SupervisedMLAlgorithm.learn(SupervisedMLAlgorithm.java:42)
	at org.aksw.limes.core.controller.MLPipeline.execute(MLPipeline.java:63)
	at org.aksw.limes.core.controller.Controller.getMapping(Controller.java:134)
	at org.aksw.limes.core.controller.Controller.main(Controller.java:45)
Caused by: java.lang.IllegalStateException: Chromosome (depth 1, index 0) requires a function or terminal of return type class org.aksw.limes.core.datastrutures.PairSimilar (sub return type 1) but there is no such node available
	at org.jgap.gp.impl.ProgramChromosome.selectNode(ProgramChromosome.java:519)
	at org.jgap.gp.impl.ProgramChromosome.growOrFullNode(ProgramChromosome.java:573)
	at org.jgap.gp.impl.ProgramChromosome.growOrFullNode(ProgramChromosome.java:654)
	at org.jgap.gp.impl.ProgramChromosome.growOrFullNode(ProgramChromosome.java:654)
	at org.jgap.gp.impl.ProgramChromosome.growOrFull(ProgramChromosome.java:273)
	at org.jgap.gp.impl.GPProgram.growOrFull(GPProgram.java:208)
	at org.jgap.gp.impl.DefaultProgramCreator.create(DefaultProgramCreator.java:35)
	at org.jgap.gp.impl.GPPopulation.create(GPPopulation.java:511)
	at org.jgap.gp.impl.GPPopulation.create(GPPopulation.java:315)
	at org.jgap.gp.impl.GPPopulation.create(GPPopulation.java:241)
	at org.jgap.gp.impl.DefaultPopulationCreator.initialize(DefaultPopulationCreator.java:68)
	at org.jgap.gp.impl.GPGenotype.randomInitialGenotype(GPGenotype.java:398)
	... 8 more
17:10:05.921 [main] ERROR org.aksw.limes.core.ml.algorithm.Eagle:109 - java.lang.IllegalStateException: Chromosome (depth 1, index 0) requires a function or terminal of return type class org.aksw.limes.core.datastrutures.PairSimilar (sub return type 1) but there is no such node available
17:10:05.921 [main] ERROR org.aksw.limes.core.ml.algorithm.Eagle:163 - No link specification calculated so far.
17:10:05.921 [main] INFO  org.aksw.limes.core.controller.Controller:147 - Mapping task finished in 957 ms
17:10:05.922 [main] INFO  org.aksw.limes.core.controller.Controller:151 - Mapping size: 0 (accepted) + 0 (need verification) = 0 (total)
17:10:05.924 [main] INFO  org.aksw.limes.core.io.serializer.SerializerFactory:15 - Getting serializer with name TAB
```

**Comment by Kleanthi** [comment]
Problem no longer occurs when I run LIMES in my computer.
